### PR TITLE
Feat/tag text shortening

### PR DESCRIPTION
**Pull request by akim316**
Closes carbon-design-system/carbon-addons-control#61

[Storybook here](https://functional-tag-storybook-static.mybluemix.net/)

### CODE REVIEW

**Comment by asudoh** [comment]
Thanks @akim316 for trying to address this area! It appears that the code attempts to do string-based shortening, which tends to cause g11n issue especially considering surrogate pair (e.g. what you'll see with `'💥'.substring(0, 1)`). I'd recommend having our designers' review to figure out the best way to address this problem space.

**Comment by akim316** [comment]
Hey akira, we are going to be creating a new issue for that, as we want to pull this in for now to work on the current project we are working on. I plan on meeting designers next week to discuss this. [Here's  the new issue.](#64)

**Comment by asudoh** [comment]
Great - Thanks @akim316! Did you mean https://github.com/carbon-design-system/carbon-addons-cloud/issues/64 as the link?

**Pull request merged**
