### PR TITLE
feat(CloudHeader): Allow a custom menu in CloudHeader

### PR DESCRIPTION
**Pull request by ajdaniel**
Allow for a custom menu icon and menu render in the Cloud Header. This can allow products to add something that doesn’t fully conform with the existing design, such as a help menu.

#### Changelog

**New**

- `customMenuIcon` and `renderCustomMenu` props for CloudHeader

Signed-off-by: Andrew J Daniel <adaniel@uk.ibm.com>

### CODE REVIEW

**Comment by joshblack** [comment]
Is this for a particular offering/portfolio @ajdaniel? Definitely am down for adding this is this is helping someone out right now. Unfortunately the UX around this will need to be considered as well, as that is the primary purpose of this component. cc @chrisconnors-ibm if you have any thoughts as well.

**Comment by ajdaniel** [comment]
@joshblack yes we are using this component in production for a watson Saas product, Conversation.

**Comment by chrisconnors-ibm** [comment]
this will be addressed as part of the new header work, not to be fixed at this time.

**Comment by ajdaniel** [comment]
@chrisconnors-ibm do you know when that might be?

**Comment by ajdaniel** [comment]
@joshblack @chrisconnors-ibm is this PR going to be approved and merged?

**Comment by joshblack** [comment]
Hey @ajdaniel! 👋 I think the last action item for this was communicated in the slack thread that we have for #carbon-design-system (I think). The hope would be to have a meeting with the relevant parties to help move this along.

**Comment by joshblack** [comment]
Hi there! The React part of this project has moved on over to `carbon-addons-cloud-react`. Going to close this PR on this project for now, but feel free to re-open on the React-based project!

**Pull request closed without merging**
